'use strict';

module.exports = {
  up: function (queryInterface, Sequelize) {
    return queryInterface.bulkInsert('Scores', [
        {
          teamId: 1,
          week1: 0,
          week2: 0,
          week3: 0,
          week4: 0,
          week5: 0,
          week6: 0,
          week7: 0,
          week8: 0,
          week9: 0,
          week10: 0,
          week11: 0,
          week12: 0,
          week13: 0,
          week14: 0,
          week15: 0,
          week16: 0,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          teamId: 2,
          week1: 0,
          week2: 0,
          week3: 0,
          week4: 0,
          week5: 0,
          week6: 0,
          week7: 0,
          week8: 0,
          week9: 0,
          week10: 0,
          week11: 0,
          week12: 0,
          week13: 0,
          week14: 0,
          week15: 0,
          week16: 0,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          teamId: 3,
          week1: 0,
          week2: 0,
          week3: 0,
          week4: 0,
          week5: 0,
          week6: 0,
          week7: 0,
          week8: 0,
          week9: 0,
          week10: 0,
          week11: 0,
          week12: 0,
          week13: 0,
          week14: 0,
          week15: 0,
          week16: 0,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          teamId: 4,
          week1: 0,
          week2: 0,
          week3: 0,
          week4: 0,
          week5: 0,
          week6: 0,
          week7: 0,
          week8: 0,
          week9: 0,
          week10: 0,
          week11: 0,
          week12: 0,
          week13: 0,
          week14: 0,
          week15: 0,
          week16: 0,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          teamId: 5,
          week1: 0,
          week2: 0,
          week3: 0,
          week4: 0,
          week5: 0,
          week6: 0,
          week7: 0,
          week8: 0,
          week9: 0,
          week10: 0,
          week11: 0,
          week12: 0,
          week13: 0,
          week14: 0,
          week15: 0,
          week16: 0,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          teamId: 6,
          week1: 0,
          week2: 0,
          week3: 0,
          week4: 0,
          week5: 0,
          week6: 0,
          week7: 0,
          week8: 0,
          week9: 0,
          week10: 0,
          week11: 0,
          week12: 0,
          week13: 0,
          week14: 0,
          week15: 0,
          week16: 0,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          teamId: 7,
          week1: 0,
          week2: 0,
          week3: 0,
          week4: 0,
          week5: 0,
          week6: 0,
          week7: 0,
          week8: 0,
          week9: 0,
          week10: 0,
          week11: 0,
          week12: 0,
          week13: 0,
          week14: 0,
          week15: 0,
          week16: 0,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          teamId: 8,
          week1: 0,
          week2: 0,
          week3: 0,
          week4: 0,
          week5: 0,
          week6: 0,
          week7: 0,
          week8: 0,
          week9: 0,
          week10: 0,
          week11: 0,
          week12: 0,
          week13: 0,
          week14: 0,
          week15: 0,
          week16: 0,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          teamId: 9,
          week1: 0,
          week2: 0,
          week3: 0,
          week4: 0,
          week5: 0,
          week6: 0,
          week7: 0,
          week8: 0,
          week9: 0,
          week10: 0,
          week11: 0,
          week12: 0,
          week13: 0,
          week14: 0,
          week15: 0,
          week16: 0,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          teamId: 10,
          week1: 0,
          week2: 0,
          week3: 0,
          week4: 0,
          week5: 0,
          week6: 0,
          week7: 0,
          week8: 0,
          week9: 0,
          week10: 0,
          week11: 0,
          week12: 0,
          week13: 0,
          week14: 0,
          week15: 0,
          week16: 0,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          teamId: 11,
          week1: 0,
          week2: 0,
          week3: 0,
          week4: 0,
          week5: 0,
          week6: 0,
          week7: 0,
          week8: 0,
          week9: 0,
          week10: 0,
          week11: 0,
          week12: 0,
          week13: 0,
          week14: 0,
          week15: 0,
          week16: 0,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          teamId: 12,
          week1: 0,
          week2: 0,
          week3: 0,
          week4: 0,
          week5: 0,
          week6: 0,
          week7: 0,
          week8: 0,
          week9: 0,
          week10: 0,
          week11: 0,
          week12: 0,
          week13: 0,
          week14: 0,
          week15: 0,
          week16: 0,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          teamId: 13,
          week1: 0,
          week2: 0,
          week3: 0,
          week4: 0,
          week5: 0,
          week6: 0,
          week7: 0,
          week8: 0,
          week9: 0,
          week10: 0,
          week11: 0,
          week12: 0,
          week13: 0,
          week14: 0,
          week15: 0,
          week16: 0,
          createdAt: new Date(),
          updatedAt: new Date()
        },
        {
          teamId: 14,
          week1: 0,
          week2: 0,
          week3: 0,
          week4: 0,
          week5: 0,
          week6: 0,
          week7: 0,
          week8: 0,
          week9: 0,
          week10: 0,
          week11: 0,
          week12: 0,
          week13: 0,
          week14: 0,
          week15: 0,
          week16: 0,
          createdAt: new Date(),
          updatedAt: new Date()
        }
    ], {});
  },

  down: function (queryInterface, Sequelize) {
    return queryInterface.bulkDelete('Scores', null, {});
  }
};
